name: EasyWarps
version: 1.0.0
author: ImperaZim 
api: [4.0.0]
main: ImperaZim\EasyWarps\Loader

permissions:
  easywarps.operator.command:
    default: op
  easywarps.default.command:
    default: true