name: EasyWarps
version: 3.0.0-BETA
authors:
  - ImperaZim

api: 5.0.0
main: imperazim\EasyWarps

depend:
  - EasyLibrary
extensions:
  Core: ">=8.2"

permissions:
  easywarps.admin:
    default: op
  easywarps.default:
    default: true
