name: EasyWarps_New
version: 1.0.0
author: ImperaZim 
api: [4.0.0]
main: ImperaZim\EasyWarps\Loader

permissions:
  warp.command:
    default: op
  warps.command:
    default: true
  warp.create:
    default: op
  warp.delete:
    default: op
